region                                   = "us-east-1" 
unique_label                             = "bryan" #enter a unique label to add to all your resource names, it will be added as 'uniquelabel-'to all your resources, for example if you set the label to bob, your resource will be bob-pipeline-tf-bucket
pipeline_state_bucket_name               = "pipeline-tf-bucket"
pipeline_locks_ddb_table_name            = "pipeline-state-lock"
codecommit_repository_name               = "pipeline-repo"
codebuild_service_role_name              = "codebuild-role"
codebuild_service_role_permissions       = ["arn:aws-us-gov:iam::aws:policy/AdministratorAccess"] #[policy]
terraform_validation_project_name        = "tf-validate"
terraform_validation_project_description = "My terraform validation project"
codebuild_compute_type                   = "BUILD_GENERAL1_SMALL"                           #BUILD_GENERAL1_SMALL
codebuild_image                          = "aws/codebuild/amazonlinux2-x86_64-standard:3.0" #aws/codebuild/amazonlinux2-x86_64-standard:3.0
codebuild_image_pull_credentials_type    = "CODEBUILD"                                      #CODEBUILD
codebuild_os_type                        = "LINUX_CONTAINER"                                #LINUX_CONTAINER
codebuild_deploy_project_name            = "codebuild-deploy"
codebuild_deploy_project_description     = "My codebuild deploy project"
validation_error_notification            = "bryan.espinosa@atl.frb.org" #needs to be an email
terraform_validation_result_bucket_name  = "result-bucket"
sns_topic_name                           = "pipeline-topic"
email_notification_endpoint              = "bryan.espinosa@atl.frb.org" #needs to be an email
codepipeline_service_role_name           = "pipeline-role"
codepipeline_name                        = "pipeline"
codepipeline_artifact_bucket             = "artifact-bucket"
lambda_role                              = "lambda-role"
cw_event_role                            = "event-role"
